[badge]
animated = true
map = 2337 
points = 20
art = "Etikals"

[conditions]
# spreadsheet said 2377
default = "M2337 X=35:70 Y=148:158 S4342=ON"

[lang.en]
name = "It's a fair price..."
condition = "Obtain the menu type 79. If you have already unlocked it, return where it can be found in Black Dust Desert."
