[badge]
animated = true
map = 4088
points = 15
art = "VoxSilentii"

[conditions]
requirements = "2kki_visit_watching_forest_a AND 2kki_visit_watching_forest_b"

[lang.en]
name = "The Forest Has Eyes"
description = "Lost in the forest's gaze, the little dreamer followed the path inwards to its lamplit heart."
condition = "Visit both sections of Watching Forest"
