[badge]
animated = true
map = 4149
points = 0
art = "3heart"
hidden = true

[conditions]
default = "M4149"

[lang.en]
name = "Cyber Locksmith"
description = "I'm gonna be king of the pirates!"
condition = "Enter the rare Keygen room of Mystery Zone B"
