[badge]
group = "4_ch"
animated = true
points = 20
art = "Ticks"

[badge.map]
id = 1350
secret = true

[conditions]
requirements = "rainbow_ruins AND rainbow_towers AND rainbow_axis AND visit_rainbow_pottery_zone AND visit_rainbow_silhouette AND rainbow_snow_plateau AND sealed_rainbow_pillars AND visit_rainbow_tiles_maze AND radiant_rainbow_reef AND visit_rainbow_road AND visit_house_over_rainbow"
# reusing `rainbow_ruins`
# reusing `rainbow_towers`
# reusing `rainbow_axis`
visit_rainbow_pottery_zone = "M1730 X=0:84 Y=0:80" # (Rainbow Pottery Zone)
visit_rainbow_silhouette = "M549"            # (Rainbow Silhouette World)
# reusing `rainbow_snow_plateau`
# reusing `sealed_rainbow_pillars`
visit_rainbow_tiles_maze = "M1102" # (Rainbow Tiles Maze)
# reusing `radiant_rainbow_reef`
visit_rainbow_road = "M1990" # (Rainbow Road)
visit_house_over_rainbow = "M812"  # (House Over The Rainbow)

[lang.en]
name = "Sunshine and Rainbows"
description = "I love colors!!!"
condition = "Visit the following rainbow worlds: Rainbow Ruins (Bright Forest), Rainbow Towers, Rainbow Axis, Rainbow Pottery Zone, Rainbow Silhouette World, Rainbow Snow Plateau, Sealed Rainbow Pillars, Rainbow Tiles Maze, Radiant Rainbow Reef, Rainbow Road, and House Over the Rainbow"

[lang.en.checkbox]
sealed_rainbow_pillars = "Sealed Rainbow Pillars"
rainbow_ruins = "Rainbow Ruins (Bright Forest)"
rainbow_towers = "Rainbow Towers"
rainbow_axis = "Rainbow Axis"
visit_rainbow_pottery_zone = "Rainbow Pottery Zone"
ch_rainbow_worlds_e = "Rainbow Silhouette World"
rainbow_snow_plateau = "Rainbow Snow Plateau"
visit_rainbow_tiles_maze = "Rainbow Tiles Maze"
radiant_rainbow_reef = "Radiant Rainbow Reef"
visit_rainbow_road = "Rainbow Road"
visit_house_over_rainbow = "House Over the Rainbow"
