[badge]
animated = true
map = 31
points = 20
art = "Anju"

[conditions]
requirements = "ly_discomfort_bath_corpse AND ly_discomfort_bath_corpse_after COUNT=1"
ly_discomfort_bath_corpse = "M31 E3"

[lang.en]
name = "Worthless"
condition = "View the \"It's not worth it\" event in Discomfort Bath"
