[badge]
animated = true
map = 94
points = 10
art = "Masky1977"

[conditions]
requirements = "visit_night_field AND visit_night_field_after_event COUNT=1"
visit_night_field = "M94"

[lang.en]
name = "Midnight Fields"
description = "Despite the darkness and slowly gathering rain, you feel a strange feeling of comfort and relief in your heart."
condition = "Visit Night Field"
