[badge]
group = "4_ch"
points = 50
art = "HenryAutumn & Komaki"
animated = true

[badge.map]
id = 56
secret = true

[conditions]
requirements = "atlantis AND neon_sea AND calcarina_sea AND azure_depths AND alrescha_sea AND pastel_pools AND watching_waters AND coral_shoal AND peaceful_shoal AND flowery_pond AND goldfish_pond AND elysium_pools AND pastel_dream_sea_a OR pastel_dream_sea_b"
calcarina_sea = "M1245"
azure_depths = "M1273 X=128:317 Y=0:149"
alrescha_sea = "M1398"
pastel_pools = "M1842"
peaceful_shoal = "M2121"
flowery_pond = "M2400"
pastel_dream_sea_a = "M3361"
pastel_dream_sea_b = "M3364"

[lang.en]
name = "Everlasting Reef"
description = "You feel safe swimming with the fish?"
condition = "Visit the following cute water worlds: Pastel Dream Sea, Alrescha Sea, Peaceful Shoal, Watching Waters, Calcarina Sea, Azure Depths, Atlantis, Neon Sea, Coral Shoal, Goldfish Pond, Flowery Ponds, Pastel Pools, Elysium Pools"

[lang.en.checkbox]
atlantis = "Atlantis"
neon_sea = "Neon Sea"
calcarina_sea = "Calcarina Sea"
azure_depths = "Azure Depths"
alrescha_sea = "Alrescha Sea"
pastel_pools = "Pastel Pools"
watching_waters = "Watching Waters"
coral_shoal = "Coral Shoal"
peaceful_shoal = "Peaceful Shoal"
flowery_pond = "Flowery Pond"
goldfish_pond = "Goldfish Pond"
elysium_pools = "Elysium Pools"
"pastel_dream_sea_a|pastel_dream_sea_b" = "Pastel Dream Sea"

