[badge]
group = "4_ch"
points = 50
art = "HenryAutumn & Komaki"
animated = true

[badge.map]
id = 56
secret = true

[conditions]
requirements = "water_world_1 AND water_world_2 AND water_world_3 AND water_world_4 AND water_world_5 AND water_world_6 AND water_world_7 AND water_world_8 AND water_world_9 AND water_world_10 AND water_world_11 AND water_world_12 AND water_world_13a OR water_world_13b"
water_world_1 = "M0056"
water_world_2 = "M0840"
water_world_3 = "M1245"
water_world_4 = "M1273 X=128:317 Y=0:149"
water_world_5 = "M1398"
water_world_6 = "M1842"
water_world_7 = "M1862"
water_world_8 = "M2058"
water_world_9 = "M2121"
water_world_10 = "M2400"
water_world_11 = "M3117"
water_world_12 = "M3224"
water_world_13a = "M3361"
water_world_13b = "M3364"

[lang.en]
name = "Everlasting Reef"
description = "You feel safe swimming with the fish?"
condition = "Visit the following cute water worlds: Pastel Dream Sea, Alrescha Sea, Peaceful Shoal, Watching Waters, Calcarina Sea, Azure Depths, Atlantis, Neon Sea, Coral Shoal, Goldfish Pond, Flowery Ponds, Pastel Pools, Elysium Pools"

[lang.en.checkbox]
water_world_1 = "Atlantis"
water_world_2 = "Neon Sea"
water_world_3 = "Calcarina Sea"
water_world_4 = "Azure Depths"
water_world_5 = "Alrescha Sea"
water_world_6 = "Pastel Pools"
water_world_7 = "Watching Waters"
water_world_8 = "Coral Shoal"
water_world_9 = "Peaceful Shoal"
water_world_10 = "Flowery Pond"
water_world_11 = "Goldfish Pond"
water_world_12 = "Elysium Pools"
water_world_13 = "Pastel Dream Sea"
