[badge]
group = "4_ch"
points = 50
art = "HenryAutumn & Komaki"

[badge.map]
id = 56
secret = true

[conditions]
requirements = "ALL"
water_world_1 = "M0056"
water_world_2 = "M0840"
water_world_3 = "M1245"
water_world_4 = "M1273"
water_world_5 = "M1398"
water_world_6 = "M1842"
water_world_7 = "M1862"
water_world_8 = "M2058"
water_world_9 = "M2121"
water_world_10 = "M2400"
water_world_11 = "M3117"
water_world_12 = "M3224"
water_world_13 = "M3361"

[lang.en]
name = "Everlasting Reef"
description = "You feel safe swimming with the fish?"
condition = "Visit the following cute water worlds: Pastel Dream Sea, Alrescha Sea, Peaceful Shoal, Watching Waters, Calcarina Sea, Azure Depths, Atlantis, Neon Sea, Coral Shoal, Goldfish Pond, Flowery Ponds, Pastel Pools, Elysium Pools"
