[badge]
points = 15
map = 3368
art = "Tanjunebi"
animated = true

[conditions]
default = "M3368 S6=ON"

[lang.en]
name = "Neil The Seal"
description = "Violence is not the answer."
condition = "Chainsaw the seal in Overwork Office"
