[badge]
points = 15
art = "Tanjunebi"
animated = true

[badge.map]
id = 2038
x = 1
y = 312

[conditions]
default = "M3368 S6=ON"

[lang.en]
name = "Neil The Seal"
description = "Violence is not the answer."
condition = "Chainsaw the seal in Overwork Office"
