[badge]
points = 15
map = 1555
art = "Aurora"
animated = true

[conditions]
default = "M1555 X=34:50 Y=72:83 S196=ON"

[lang.en]
name = "Rap Fox"
description = "What I gotta get it through to you I'm supervixen?"
condition = "Use the Crossing effect near the singing fox in Celestial Night"
