[badge]
points = 20
map = 65
art = "Paraverdant"
animated = true

[conditions]
default = "M65 X=0:105 Y=19:119 S671=ON"

[lang.en]
name = "The Lady's Tome"
description = "Hi there..."
condition = "Obtain Menu Theme #91 in Highway. If already obtained, return to the room where you have done so."
