[badge]
points = 20
map = 65
art = "Paraverdant"
animated = true

[conditions]
default = "M65 X=0:19 Y=105:119 S671=ON"

[lang.en]
name = "The Lady's Tome"
description = "Hi there..."
condition = "Obtain the menu type 91. If you have already unlocked it, return where it can be found in Highway."
