[badge]
points = 20
art = "aukse"
animated = true

[badge.map]
id = 3154
x = 17
y = 218

[conditions]
default = "M3154 X=17:28 Y=218:220"

[lang.en]
name = "Midnight Shack"
description = "When the stars come out, they lead the way here."
condition = "Visit the shack in Star Cubes World"
