[badge]
points = 20
art = "Staghouse33"
animated = true

[badge.map]
id = 3154
x = 17
y = 218

[conditions]
default = "M3154 X=17:28 Y=218:220"

[lang.en]
name = "Where the starlight rest"
description = "A small, cozy haven, glimpsed through the graveyard of fossilized stars reached by a long journey."
condition = "Visit the shack in Star Cubes World"
