[badge]
points = 20
art = "Paraverdant"
animated = true

[badge.map]
id = 3368
x = 121
y = 314

[conditions]
secret = true
default = "M3368 X=0:299 Y=250:364"

[lang.en]
name = "Virulent Remedies"
description = "Seek the cure with sickness."
condition = "Visit Hemlock Lab"
