[badge]
points = 25
map = 3888
art = "HenryAutumn"

[conditions]
default = "M3888"

[lang.en]
name = "Sister of The Void"
description = "Consumed by Abyss: Lost Urotsuki"
condition = "Enter Abyss	Map"
