[badge]
points = 20
art = "vena"

[badge.map]
id = 2289
x = 44
y = 34

[conditions]
default = "M2289"

[lang.en]
name = "Meowing Forest"
description = "Home is where the cats are."
condition = "Visit Calico Forest"
