[badge]
animated = true
map = 126
points = 15
art = "LittleCherry"

[conditions]
requirements = "cold_a_effect OR cold_a_effect_after_event"
cold_a_effect = "M126 E16"
cold_a_effect_after_event = "M131 S270=ON"

[lang.en]
name = "A"
description = "aA aaA aAa a Aaaa a Aa"
condition = "Obtain the A effect. If you have already obtained it, return to the area where you have done so."
