[badge]
map = 3657
points = 15
art = "Kantyo"

[conditions]
default = "M3657 E43"

[lang.en]
name = "The Twin Eyes that Hold Two Worlds"
description = "Beneath shadowed white, two colors awaken."
condition = "Interact with Landlady in Server Not Found "
