[badge]
animated = true
map = 135
points = 15
art = "visc3ra"

[conditions]
default = "M135"

[lang.en]
name = "Desired Constellation"
description = "With a palm full of stars, I throw them like dice.."
condition = "Visit Star World"
