[badge]
animated = true
art = "aronek & emocore"
hidden = true

[badge.map]
id = 3368
y = 250

[conditions]
default = "M3368 X=271:287 Y=272:278"

[lang.en]
name = "Lonely Experiment"
description = "Do not allow unauthorized personnel to enter the ██████████ ████. DO NOT allow anyone to see ███ ████. You must remember that ███ ██ ███ ██████ ██████████. Failure to comply will result in ██████ ██████████. "
condition = "Find the girl in the Hemlock Lab"
