[badge]
animated = true
map = 176
points = 15
art = "dawnchorrus"

[conditions]
default = "M176 V3930=500001"

[lang.en]
name = "I'm a kitty Cat!"
condition = "Interact with the Cat costume with the lantern effect equiped in Dressing Room"
