[badge]
animated = true
map = 4086
points = 20
art = "Michi"

[conditions]
default = "M4086 X=295:314 Y=87:101"
secret = true

[lang.en]
name = "Distorted Familiarity"
description = "A corrupted ruin of what once was."
condition = "Visit the mountain outlook area of Dreadful City"
