[badge]
animated = true
map = 3592
points = 20
art = "Etikals"

[conditions]
default = "M3592 S845=ON"

[lang.en]
name = "Menu Overload"
description = "This is why you should never spam click if it lags"
condition = "Obtain the menu type 88. If you have already unlocked it, return where it can be found in The Desktop."
