[badge]
points = 15
map = 99
art = "thatdolphin"
animated = true

[conditions]
requirements = "aitsuki_trenchcoat OR aitsuki_trenchcoat_b"
aitsuki_trenchcoat = "M99 S56=ON"
aitsuki_trenchcoat_b = "M99 V14=8"

[lang.en]
name = "Elementary, my dear Aitsuki."
description = "\"You see, but you do not observe.\""
condition = "Obtain the Trenchcoat effect. If you have already unlocked it, return to Bathroom."
