[badge]
points = 10
map = 25
art = "Michi"
animated = true

[conditions]
default = "M25"

[lang.en]
name = "Crimson Red Prairie"
description = "Traversing the vast scarlet dunes"
condition = "Visit Crimson Dunes"
