[badge]
animated = true
map = 2276
points = 15
art = "AduriteStar"

[conditions]
default = "M2295 X=0:199 Y=224:246 S128=ON"

[lang.en]
name = "Silly Disguise"
description = "Pump it up kitty! Just pump it up kitty cat. Where you at? There you go, put two paws on the floor Two in the air and then just.. Go kitty Go kitty Go kitty go! And just Ride kitty Ride kitty Ride kitty roll!"
condition = "Use the glasses effect near the purple girl NPC in Worksite"
