[badge]
animated = true
points = 15
art = "3heart"

[badge.map]
id = 1826
y = 120

[conditions]
default = "M1826 S5012=ON"

[lang.en]
name = "Thirsty Dolphin"
description = "You're not drinking that coffee... right?"
condition = "Interact with the dolphin in Hexagonal Pillar Passage's isolated section"
