[badge]
animated = true
map = 148
points = 15
art = "Komaki"

[conditions]
mushroom_cathedral_a = "M148 S534=OFF"
mushroom_cathedral_b = "M148 S534=ON"

[lang.en]
name = "Mushroom Time Church"
description = "Time really flew fast in here huh?"
condition = "See both the day and night versions of Mushroom Cathedral"
