[badge]
points = 15
art = "dawnchorrus"

[badge.map]
id = 1826
x = 1
y = 18

[conditions]
default = "M1826 X=29:42 Y=56:62 S6=ON"

[lang.en]
name = "Coffee, Coming Right Up!"
description = "Have some of the finest coffee the dream world has to offer!"
condition = "Drink coffee at the Critter Village cafe"
