[badge]
animated = true
map = 13
points = 10
art = "desktopghost"

[conditions]
default = "M13 S23=ON"

[lang.en]
name = "Glittering Seashells"
condition = "Use the Light Bug effect in the Night version of Seaside"
