[badge]
map = 290
points = 15
art = "tophat"

[conditions]
default = "M290"

[lang.en]
name = "Peeling, Rotting, Deteriorating"
description = "A memory so rusty inside your head it hurts to remember. But even yet, it's beautiful to remember, isn't it?"
condition = "Visit Deterioration"
