[badge]
map = 2483
points = 15
art = "tophat"

[conditions]
default = "M2483 X=120:131 Y=82:87"

[lang.en]
name = "Rocky-Looking Thing"
description = "But here's the uhh...uhhhhhhh.....Whatever this is."
condition = "See the rocky-like alien in Alien World"
