[badge]
animated = true
map = 1544
points = 15
art = "3heart"

[conditions]
requirements = "pastel_sky_park_secret_a OR pastel_sky_park_secret_b OR pastel_sky_park_secret_c"

pastel_sky_park_secret_a = "M1544 S131=ON" # Eyeball Bomb equip
pastel_sky_park_secret_b = "M1544 S153=ON" # Marginal equip
pastel_sky_park_secret_c = "M1544 S168=ON" # Glasses use

[lang.en]
name = "Harmless Cute Ball"
condition = "Reveal the secret of Pastel Sky Park"
