[badge]
animated = true
map = 96
points = 15
art = "Canto Mk. 6"

[conditions]
default = "M96 S107=ON"

[lang.en]
name = "Vivid Wave's Key"
description = "A pig with a drum in a cheese maze."
condition = "Obtain the Drum effect. If already obtained, return to where it can be found in Cheese Maze."
