[badge]
map = 19
points = 20
art = "tophat"

[conditions]
default = "M19 V66=1"

[lang.en]
name = "The Weirdo That Comes Out At Midnight"
description = "What was that"
condition = "See the Midnight Yellowman in Mikan's Bedroom during midnight."
