[badge]
group = "4_ch"
animated = true
points = 35
art = "Aurora"

[badge.map]
id = 187
secret = true

[conditions]
requirements = "visit_docks AND visit_lezaxzasea_docks AND visit_streetlight_docks AND visit_flooded_docks AND visit_barley_docks AND visit_dreadful_docks AND visit_rainy_docks AND visit_blinking_docks AND visit_serene_docks AND wan_lotus_docks AND visit_white_pillar_docks AND visit_birch_tree_docks AND visit_sweet_pink_docks"
visit_docks = "M187"
visit_lezaxzasea_docks = "M3403"
visit_streetlight_docks = "M1824"
visit_flooded_docks = "M2887"
visit_barley_docks = "M3459"
visit_dreadful_docks = "M1302 X=0:126 Y=0:136"
visit_rainy_docks = "M846"
visit_blinking_docks = "M2637"
visit_serene_docks = "M1975"
# reusing `wan_lotus_docks`
visit_white_pillar_docks = "M2951"
visit_birch_tree_docks = "M2343"
visit_sweet_pink_docks = "M2208"

[lang.en]
name = "What's Up, Dock?"
description = "Either you love maritime infrastructure, or you may be a boat. Either way, this is your token of dock appreciation!"
condition = "Visit the following worlds themed around docks: Docks, Lezaxzasea Docks, Streetlight Docks, Flooded Docks, Barley Docks, Dreadful Docks, Rainy Docks, Blinking Docks, Serene Docks, Wan Lotus Docks, White Pillar Docks, Birch Tree Docks, and Sweet Pink Docks"

[lang.en.combo]
visit_docks = "Docks"
visit_lezaxzasea_docks = "Lezaxzasea Docks"
visit_streetlight_docks = "Streetlight Docks"
visit_flooded_docks = "Flooded Docks"
visit_barley_docks = "Barley Docks"
visit_dreadful_docks = "Dreadful Docks"
visit_rainy_docks = "Rainy Docks"
visit_blinking_docks = "Blinking Docks"
visit_serene_docks = "Serene Docks"
wan_lotus_docks = "Wan Lotus Docks"
visit_white_pillar_docks = "White Pillar Docks"
visit_birch_tree_docks = "Birch Tree Docks"
visit_sweet_pink_docks = "Sweet Pink Docks"
