[badge]
animated = true
map = 1557
points = 15
art = "Ticks"
secret = true

[conditions]
default = "M1557 X=11:41 Y=72:82 S168=ON"

[lang.en]
name = "I’m the one who knows them best, every crack in the asphalt’s shape and location."
description = "My ears hear the sound of laughter."
condition = "Use the Glasses effect to reveal the Lamplighter in Frozen Disco"
