[badge]
group = "4ch"
animated = true
points = 30
art = "HenryAutumn"
overlay = 4

[badge.map]
id = 3591
secret = true

[conditions]
requirements = "visit_the_desktop AND file_viewer AND visit_azure_overdose_zone AND visit_sink_catalog AND visit_ascii_symbol_zone AND tranquil_park"
visit_the_desktop = "M3591"
# reusing `file_viewer`
visit_azure_overdose_zone = "M2879"
visit_sink_catalog = "M3634"
visit_ascii_symbol_zone = "M3219"
# reusing `tranquil_park`

[lang.en]
name = "Window to the Past"
description = "Nostalgia is a beautiful but melancholic feeling."
condition = "Visit the following worlds themed around desktops: The Desktop, File Viewer, Azure Overdose Zone, Sink Catalog, ASCII Symbol World, and Tranquil Park"

[lang.en.checkbox]
visit_the_desktop = "The Desktop"
file_viewer = "File Viewer"
visit_azure_overdose_zone = "Azure Overdose Zone"
visit_sink_catalog = "Sink Catalog"
visit_ascii_symbol_zone = "ASCII Symbol Zone"
tranquil_park = "Tranquil Park"
