[badge]
animated = true
map = 9
points = 25
art = "Aurora"

[conditions]
requirements = "muma_realm_orb_empty AND realm_of_the_orb_snake_a COUNT=1"
muma_realm_orb_empty = "M9 E6 INDIRECT S217=ON"

[lang.en]
name = "Caution! Fragile!"
description = "One day, she fell into her creation, and was shattered across dream and reality."
condition = "Witness the Realm of the Orb's Empty event"
