[badge]
animated = true
points = 15
art = "Anju"

[badge.map]
id = 4088
x = 258

[conditions]
default = "M4088 X=258:279 Y=0:15"

[lang.en]
name = "Terra Incognita"
description = "As if I can never witness the exact moment a flower blooms, things never go as planned; an image that surpasses all expectations is seared into the back of my eyelids."
condition = "See the red hands making a heart pose in Crimson Drains"
