[badge]
map = 111
points = 15
art = "HenryAutumn"

[conditions]
default = "M111 X=92:201 Y=7:136 S6=ON"

[lang.en]
name = "Friend Shaped"
description = "Fat and happy!"
condition = "Obtain the Fatten effect. If you have already unlocked it, return to Docks B."
