[badge]
map = 65
points = 10
art = "systemaciel"

[conditions]
requirements = "ly_victim_effect OR ly_victim_effect_after_event"
default = "M65 S45=ON"

[lang.en]
name = "You Smell So Red"
description = "What did you do?"
condition = "Obtain the Victim effect. If you have already unlocked it, return to -30."
