[badge]
group = "2_kb"
animated = true
map = 177
points = 10
art = "Aurora"

[conditions]
default = "M408 X=0:89 Y=145:159"

[lang.en]
name = "City Stars"
description = "I think I love every person behind every window. I love you, people, for being my stars. You are lovely for tonight..."
condition = "Visit the Rainy Street from Blacklight Bar or Pink Desert"
